# Generated by Django 3.1.2 on 2023-07-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_abarrote_herramienta_outdoor_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='contact',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='numerodpto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
